language: java
jdk:
  - openjdk11

sudo: false
os: linux

cache:
  directories:
  - $HOME/.gradle/caches

before_install:
  - export DISPLAY=:99.0
install: true

before_script:
  - chmod +x ./gradlew
script: ./gradlew build

